// SSR landing page — /guia/[slug]
// SEO indexable page generated by AI from trending searches.
// Includes schema.org Article + FAQPage + BreadcrumbList + ItemList for rich results.

import { db } from "@/lib/db";
import { parseProduct } from "@/lib/api-helpers";
import { STORES, formatPEN } from "@/lib/constants";
import { SiteHeader } from "@/components/site/site-header";
import { SiteFooter } from "@/components/site/site-footer";
import { ProductImage } from "@/components/blackbox/product-image";
import { ScoreRing } from "@/components/blackbox/score-ring";
import { ClassificationBadge } from "@/components/blackbox/badges";
import { classificationOf, scoreOf } from "@/hooks/use-blackbox";
import { OfferButton } from "@/components/site/offer-button";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Sparkles, HelpCircle, ArrowRight, TrendingUp } from "lucide-react";

interface PageProps {
  params: Promise<{ slug: string }>;
}

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://blackbox.app";

async function getLanding(slug: string) {
  const landing = await db.landingPage.findUnique({ where: { slug } });
  if (!landing || landing.status !== "published") return null;

  // Parse JSON fields
  let body: Array<{ type: string; heading: string; content: string }> = [];
  let faqs: Array<{ q: string; a: string }> = [];
  let productIds: string[] = [];
  try { body = JSON.parse(landing.body); } catch { /* empty */ }
  try { faqs = JSON.parse(landing.faqs); } catch { /* empty */ }
  try { productIds = JSON.parse(landing.productIds); } catch { /* empty */ }

  // Fetch related products
  const productsRaw = productIds.length
    ? await db.product.findMany({
        where: { id: { in: productIds }, isActive: true, contributionStatus: "approved" },
        include: {
          offers: { orderBy: { price: "asc" } },
          aiScores: { orderBy: { updatedAt: "desc" }, take: 1 },
        },
      })
    : [];
  const products = productsRaw.map(parseProduct);

  return { ...landing, body, faqs, productIds, products };
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const landing = await getLanding(slug);
  if (!landing) return { title: "Guía no encontrada · BLACKBOX" };

  const title = landing.metaTitle || landing.title;
  const description = landing.metaDescription || landing.intro.slice(0, 160);
  const url = `/guia/${landing.slug}`;

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      type: "article",
      siteName: "BLACKBOX",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export const revalidate = 3600;

export default async function LandingPage({ params }: PageProps) {
  const { slug } = await params;
  const landing = await getLanding(slug);
  if (!landing) notFound();

  const { products, body, faqs } = landing;

  // Schema.org JSON-LD
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: landing.h1,
    description: landing.metaDescription || landing.intro.slice(0, 160),
    author: { "@type": "Organization", name: "BLACKBOX IA" },
    publisher: {
      "@type": "Organization",
      name: "BLACKBOX",
      logo: { "@type": "ImageObject", url: `${SITE_URL}/logo.svg` },
    },
    datePublished: landing.createdAt.toISOString(),
    dateModified: landing.updatedAt.toISOString(),
  };

  const faqSchema = faqs.length > 0 ? {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  } : null;

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Inicio", item: SITE_URL },
      { "@type": "ListItem", position: 2, name: "Guías", item: `${SITE_URL}/guias` },
      { "@type": "ListItem", position: 3, name: landing.h1, item: `${SITE_URL}/guia/${landing.slug}` },
    ],
  };

  const itemListSchema = products.length > 0 ? {
    "@context": "https://schema.org",
    "@type": "ItemList",
    itemListElement: products.map((p, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: p.name,
      url: `${SITE_URL}/producto/${p.slug}`,
    })),
  } : null;

  const schemas = [articleSchema, breadcrumbSchema];
  if (faqSchema) schemas.push(faqSchema);
  if (itemListSchema) schemas.push(itemListSchema);

  return (
    <>
      <SiteHeader />
      <main className="flex-1">
        {/* JSON-LD */}
        {schemas.map((schema, i) => (
          <script
            key={i}
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
          />
        ))}

        <article className="mx-auto max-w-3xl px-4 py-10">
          {/* Breadcrumbs */}
          <nav className="mb-6 flex items-center gap-1.5 text-xs text-muted-foreground" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-foreground">Inicio</Link>
            <span className="text-muted-foreground/40">/</span>
            <span className="text-foreground">Guía</span>
            <span className="text-muted-foreground/40">/</span>
            <span className="truncate text-foreground">{landing.title}</span>
          </nav>

          {/* Title */}
          <div className="mb-6">
            <span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1 text-xs font-medium text-emerald-300">
              <Sparkles className="h-3 w-3" />
              Guía de compra con IA
            </span>
            <h1 className="mt-4 text-4xl font-bold leading-tight tracking-tight sm:text-5xl">
              {landing.h1}
            </h1>
          </div>

          {/* Intro */}
          <div className="prose prose-invert max-w-none">
            <p className="text-lg leading-relaxed text-foreground/90">{landing.intro}</p>
          </div>

          {/* Related products */}
          {products.length > 0 && (
            <section className="mt-10">
              <h2 className="mb-5 flex items-center gap-2 text-2xl font-bold tracking-tight">
                <TrendingUp className="h-5 w-5 text-emerald-400" />
                Mejores opciones
              </h2>
              <div className="space-y-4">
                {products.map((p) => {
                  const best = p.offers?.[0];
                  return (
                    <div
                      key={p.id}
                      className="flex items-center gap-4 rounded-2xl border border-border/40 glass p-4 transition-all hover:border-emerald-400/30 hover:shadow-soft"
                    >
                      <Link href={`/producto/${p.slug}`} className="relative h-20 w-20 shrink-0 overflow-hidden rounded-xl border border-border/40 bg-muted/20">
                        <ProductImage src={p.images?.[0]} alt={p.name} className="h-full w-full" />
                      </Link>
                      <div className="min-w-0 flex-1">
                        <Link href={`/producto/${p.slug}`}>
                          <h3 className="line-clamp-1 text-sm font-semibold hover:text-emerald-400">{p.name}</h3>
                        </Link>
                        <div className="mt-1 flex items-center gap-2">
                          <ClassificationBadge classification={classificationOf(p)} />
                          {best && (
                            <span className="text-sm font-bold text-emerald-400">{formatPEN(best.price)}</span>
                          )}
                        </div>
                      </div>
                      <div className="shrink-0">
                        <ScoreRing score={scoreOf(p)} classification={classificationOf(p)} size={44} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>
          )}

          {/* Body sections */}
          {body.length > 0 && (
            <div className="mt-10 space-y-8">
              {body.map((section, i) => (
                <section key={i}>
                  <h2 className="mb-3 text-2xl font-bold tracking-tight">{section.heading}</h2>
                  <div className="text-[15px] leading-relaxed text-foreground/80">
                    {section.content.split("\n").map((para, j) => (
                      <p key={j} className="mb-3">{para}</p>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          )}

          {/* FAQs */}
          {faqs.length > 0 && (
            <section className="mt-10 rounded-3xl border border-border/40 glass p-6 shadow-soft">
              <div className="mb-5 flex items-center gap-2.5">
                <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-primary/10">
                  <HelpCircle className="h-4 w-4 text-primary" />
                </span>
                <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Preguntas frecuentes
                </h2>
              </div>
              <div className="divide-y divide-border/40">
                {faqs.map((faq, i) => (
                  <div key={i} className="py-4">
                    <h3 className="text-sm font-semibold text-foreground">{faq.q}</h3>
                    <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{faq.a}</p>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* CTA */}
          <div className="mt-10 rounded-3xl border border-emerald-400/20 bg-gradient-to-br from-emerald-500/[0.08] to-transparent p-6 text-center">
            <p className="text-sm text-muted-foreground">
              ¿Buscas algo más? BLACKBOX compara precios en Amazon, Temu y Falabella.
            </p>
            <Link
              href="/"
              className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-2.5 text-sm font-semibold text-emerald-950 shadow-soft transition-all hover:bg-emerald-400 hover:shadow-float"
            >
              Explorar productos
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </article>
      </main>
      <SiteFooter />
    </>
  );
}
